### PR TITLE
Enhancement: Add link to source to `composer.json`

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] adds a link to the source to `composer.json`

Follows https://github.com/php-fig/simple-cache/pull/31.

💁‍♂️ For reference, see https://getcomposer.org/doc/04-schema.md#support.

### CODE REVIEW

**Review by dbu — APPROVED** [review]
thanks, seems like a good idea to me for when people installed this without git and therefore the link to the source is lost.

**Comment by localheinz** [comment]
@dbu 

It's also nice for people who navigate to `composer.json` of this package when they install it with `composer` and want to navigate to the source. 

Currently there are some packages in the @php-fig organization that use the [`homepage`](https://getcomposer.org/doc/04-schema.md#homepage) field to link to the package, others use the `homepage` field to link to https://www.php-fig.org.

**Comment by dbu** [comment]
thank you. https://github.com/php-fig/http-client/releases/tag/1.0.3

**Comment by localheinz** [comment]
Thank you, @dbu!

**Pull request merged**
